# Form implementation generated from reading ui file 'copyright.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CopyrightDialog(object):
    def setupUi(self, CopyrightDialog):
        CopyrightDialog.setObjectName("CopyrightDialog")
        CopyrightDialog.resize(667, 355)
        self.label = QtWidgets.QLabel(parent=CopyrightDialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 491, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=CopyrightDialog)
        self.label_2.setGeometry(QtCore.QRect(160, 80, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.url_label = QtWidgets.QLabel(parent=CopyrightDialog)
        self.url_label.setGeometry(QtCore.QRect(40, 130, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.url_label.setFont(font)
        self.url_label.setObjectName("url_label")
        self.label_3 = QtWidgets.QLabel(parent=CopyrightDialog)
        self.label_3.setGeometry(QtCore.QRect(80, 160, 481, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(CopyrightDialog)
        QtCore.QMetaObject.connectSlotsByName(CopyrightDialog)

    def retranslateUi(self, CopyrightDialog):
        _translate = QtCore.QCoreApplication.translate
        CopyrightDialog.setWindowTitle(_translate("CopyrightDialog", "CopyRight"))
        self.label.setText(_translate("CopyrightDialog", "The software is completely free and open-source"))
        self.label_2.setText(_translate("CopyrightDialog", "You can view the source code from "))
        self.url_label.setText(_translate("CopyrightDialog", "https://github.com/anonymousException/renpy-translator"))
        self.label_3.setText(_translate("CopyrightDialog", "This item is available for research and study. In no event shall the author or copyright holder be liable for any claims, damages, or other liabilities arising out of or in connection with the software or the use of the software or other dealings with the software, whether in an action in contract, an action for infringement, or any other proceeding"))
