# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'custom_engine.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_CustomDialog(object):
    def setupUi(self, CustomDialog):
        if not CustomDialog.objectName():
            CustomDialog.setObjectName(u"CustomDialog")
        CustomDialog.resize(1261, 667)
        self.label = QLabel(CustomDialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 51, 21))
        self.nameLineEdit = QLineEdit(CustomDialog)
        self.nameLineEdit.setObjectName(u"nameLineEdit")
        self.nameLineEdit.setGeometry(QRect(80, 90, 501, 20))
        self.label_2 = QLabel(CustomDialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 140, 51, 21))
        self.urlLineEdit = QLineEdit(CustomDialog)
        self.urlLineEdit.setObjectName(u"urlLineEdit")
        self.urlLineEdit.setGeometry(QRect(80, 140, 501, 20))
        self.keyCheckBox = QCheckBox(CustomDialog)
        self.keyCheckBox.setObjectName(u"keyCheckBox")
        self.keyCheckBox.setGeometry(QRect(20, 190, 161, 20))
        self.secretCheckBox = QCheckBox(CustomDialog)
        self.secretCheckBox.setObjectName(u"secretCheckBox")
        self.secretCheckBox.setGeometry(QRect(210, 190, 191, 20))
        self.queueCheckBox = QCheckBox(CustomDialog)
        self.queueCheckBox.setObjectName(u"queueCheckBox")
        self.queueCheckBox.setGeometry(QRect(20, 230, 551, 20))
        self.selectScriptBtn = QPushButton(CustomDialog)
        self.selectScriptBtn.setObjectName(u"selectScriptBtn")
        self.selectScriptBtn.setGeometry(QRect(500, 265, 81, 41))
        self.selectScriptText = QTextEdit(CustomDialog)
        self.selectScriptText.setObjectName(u"selectScriptText")
        self.selectScriptText.setGeometry(QRect(80, 265, 421, 41))
        self.label_3 = QLabel(CustomDialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 270, 31, 31))
        self.label_3.setWordWrap(True)
        self.renameScriptCheckBox = QCheckBox(CustomDialog)
        self.renameScriptCheckBox.setObjectName(u"renameScriptCheckBox")
        self.renameScriptCheckBox.setGeometry(QRect(20, 320, 111, 20))
        self.label_4 = QLabel(CustomDialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 320, 54, 20))
        self.renameScriptLineEdit = QLineEdit(CustomDialog)
        self.renameScriptLineEdit.setObjectName(u"renameScriptLineEdit")
        self.renameScriptLineEdit.setGeometry(QRect(210, 320, 371, 20))
        self.selectSourceText = QTextEdit(CustomDialog)
        self.selectSourceText.setObjectName(u"selectSourceText")
        self.selectSourceText.setGeometry(QRect(80, 375, 421, 41))
        self.renameSourceCheckBox = QCheckBox(CustomDialog)
        self.renameSourceCheckBox.setObjectName(u"renameSourceCheckBox")
        self.renameSourceCheckBox.setGeometry(QRect(20, 430, 111, 20))
        self.renameSourceLineEdit = QLineEdit(CustomDialog)
        self.renameSourceLineEdit.setObjectName(u"renameSourceLineEdit")
        self.renameSourceLineEdit.setGeometry(QRect(210, 430, 371, 20))
        self.selectSourceBtn = QPushButton(CustomDialog)
        self.selectSourceBtn.setObjectName(u"selectSourceBtn")
        self.selectSourceBtn.setGeometry(QRect(500, 375, 81, 41))
        self.label_5 = QLabel(CustomDialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 380, 41, 31))
        self.label_5.setWordWrap(True)
        self.label_6 = QLabel(CustomDialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 430, 54, 20))
        self.label_7 = QLabel(CustomDialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 485, 41, 31))
        self.label_7.setWordWrap(True)
        self.selectTargetText = QTextEdit(CustomDialog)
        self.selectTargetText.setObjectName(u"selectTargetText")
        self.selectTargetText.setGeometry(QRect(80, 480, 421, 41))
        self.label_8 = QLabel(CustomDialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 535, 54, 20))
        self.renameTargetLineEdit = QLineEdit(CustomDialog)
        self.renameTargetLineEdit.setObjectName(u"renameTargetLineEdit")
        self.renameTargetLineEdit.setGeometry(QRect(210, 535, 371, 20))
        self.renameTargetCheckBox = QCheckBox(CustomDialog)
        self.renameTargetCheckBox.setObjectName(u"renameTargetCheckBox")
        self.renameTargetCheckBox.setGeometry(QRect(20, 535, 111, 20))
        self.selectTargetBtn = QPushButton(CustomDialog)
        self.selectTargetBtn.setObjectName(u"selectTargetBtn")
        self.selectTargetBtn.setGeometry(QRect(500, 480, 81, 41))
        self.label_9 = QLabel(CustomDialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(680, 131, 81, 16))
        self.engineComboBox = QComboBox(CustomDialog)
        self.engineComboBox.setObjectName(u"engineComboBox")
        self.engineComboBox.setGeometry(QRect(840, 29, 221, 22))
        self.label_10 = QLabel(CustomDialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(680, 31, 161, 16))
        self.label_11 = QLabel(CustomDialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(680, 79, 54, 16))
        self.testButton = QPushButton(CustomDialog)
        self.testButton.setObjectName(u"testButton")
        self.testButton.setGeometry(QRect(900, 310, 121, 24))
        self.secretEdit = QLineEdit(CustomDialog)
        self.secretEdit.setObjectName(u"secretEdit")
        self.secretEdit.setGeometry(QRect(760, 129, 411, 20))
        self.keyEdit = QLineEdit(CustomDialog)
        self.keyEdit.setObjectName(u"keyEdit")
        self.keyEdit.setGeometry(QRect(760, 77, 411, 20))
        self.detailLabel = QLabel(CustomDialog)
        self.detailLabel.setObjectName(u"detailLabel")
        self.detailLabel.setGeometry(QRect(1070, 30, 111, 21))
        font = QFont()
        font.setUnderline(True)
        self.detailLabel.setFont(font)
        self.sourceComboBox = QComboBox(CustomDialog)
        self.sourceComboBox.setObjectName(u"sourceComboBox")
        self.sourceComboBox.setGeometry(QRect(760, 225, 411, 22))
        self.targetComboBox = QComboBox(CustomDialog)
        self.targetComboBox.setObjectName(u"targetComboBox")
        self.targetComboBox.setGeometry(QRect(760, 180, 411, 22))
        self.label_12 = QLabel(CustomDialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(680, 175, 41, 31))
        self.label_13 = QLabel(CustomDialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(680, 220, 41, 31))
        self.label_14 = QLabel(CustomDialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(680, 282, 101, 16))
        self.untranslatedEdit = QLineEdit(CustomDialog)
        self.untranslatedEdit.setObjectName(u"untranslatedEdit")
        self.untranslatedEdit.setGeometry(QRect(790, 280, 381, 20))
        self.logTextEdit = QTextEdit(CustomDialog)
        self.logTextEdit.setObjectName(u"logTextEdit")
        self.logTextEdit.setGeometry(QRect(680, 390, 561, 271))
        self.logTextEdit.setReadOnly(True)
        self.clearLogBtn = QPushButton(CustomDialog)
        self.clearLogBtn.setObjectName(u"clearLogBtn")
        self.clearLogBtn.setGeometry(QRect(920, 360, 75, 24))
        self.label_15 = QLabel(CustomDialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 35, 141, 16))
        self.customComboBox = QComboBox(CustomDialog)
        self.customComboBox.setObjectName(u"customComboBox")
        self.customComboBox.setGeometry(QRect(170, 30, 411, 22))
        self.saveButton = QPushButton(CustomDialog)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(240, 600, 121, 24))
        self.saveKeySecretCheckBox = QCheckBox(CustomDialog)
        self.saveKeySecretCheckBox.setObjectName(u"saveKeySecretCheckBox")
        self.saveKeySecretCheckBox.setGeometry(QRect(160, 570, 301, 20))
        self.deleteButton = QPushButton(CustomDialog)
        self.deleteButton.setObjectName(u"deleteButton")
        self.deleteButton.setGeometry(QRect(240, 640, 121, 24))

        self.retranslateUi(CustomDialog)

        QMetaObject.connectSlotsByName(CustomDialog)
    # setupUi

    def retranslateUi(self, CustomDialog):
        CustomDialog.setWindowTitle(QCoreApplication.translate("CustomDialog", u"Custom Translation Engine", None))
        self.label.setText(QCoreApplication.translate("CustomDialog", u"name", None))
        self.nameLineEdit.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"relative to Active Translation Engine", None))
        self.label_2.setText(QCoreApplication.translate("CustomDialog", u"url", None))
        self.urlLineEdit.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"relative to detail information", None))
        self.keyCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Key Support(API_KEY)", None))
        self.secretCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Secret Support(API_SECRET)", None))
        self.queueCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Queue Support (Can the api support list input in one request such as:['Hello','World'])", None))
        self.selectScriptBtn.setText(QCoreApplication.translate("CustomDialog", u"...", None))
#if QT_CONFIG(tooltip)
        self.selectScriptText.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.selectScriptText.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"input or choose or drag the python script which supports translation api.  The script will be copied to 'custom_engine' folder", None))
        self.label_3.setText(QCoreApplication.translate("CustomDialog", u"script", None))
        self.renameScriptCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Rename Script", None))
        self.label_4.setText(QCoreApplication.translate("CustomDialog", u"rename", None))
        self.renameScriptLineEdit.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"rename the  script name in  'custom engine' folder", None))
#if QT_CONFIG(tooltip)
        self.selectSourceText.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.selectSourceText.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"input or choose or drag the source language file which applies language map.  The file will be copied to 'supported_language' folder", None))
        self.renameSourceCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Rename Source", None))
        self.renameSourceLineEdit.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"rename the  source name in  'supported_language' folder", None))
        self.selectSourceBtn.setText(QCoreApplication.translate("CustomDialog", u"...", None))
        self.label_5.setText(QCoreApplication.translate("CustomDialog", u"source", None))
        self.label_6.setText(QCoreApplication.translate("CustomDialog", u"rename", None))
        self.label_7.setText(QCoreApplication.translate("CustomDialog", u"target", None))
#if QT_CONFIG(tooltip)
        self.selectTargetText.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.selectTargetText.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"input or choose or drag the target language file which applies language map.  The file will be copied to 'supported_language' folder", None))
        self.label_8.setText(QCoreApplication.translate("CustomDialog", u"rename", None))
        self.renameTargetLineEdit.setPlaceholderText(QCoreApplication.translate("CustomDialog", u"rename the  source name in  'supported_language' folder", None))
        self.renameTargetCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Rename Target", None))
        self.selectTargetBtn.setText(QCoreApplication.translate("CustomDialog", u"...", None))
        self.label_9.setText(QCoreApplication.translate("CustomDialog", u"APP_SECRET:", None))
        self.label_10.setText(QCoreApplication.translate("CustomDialog", u"Active Translation Engine:", None))
        self.label_11.setText(QCoreApplication.translate("CustomDialog", u"API_KEY:", None))
        self.testButton.setText(QCoreApplication.translate("CustomDialog", u"Test", None))
        self.secretEdit.setText("")
        self.detailLabel.setText(QCoreApplication.translate("CustomDialog", u"detail information", None))
        self.label_12.setText(QCoreApplication.translate("CustomDialog", u"target", None))
        self.label_13.setText(QCoreApplication.translate("CustomDialog", u"source", None))
        self.label_14.setText(QCoreApplication.translate("CustomDialog", u"untranslated text", None))
        self.untranslatedEdit.setText("")
        self.clearLogBtn.setText(QCoreApplication.translate("CustomDialog", u"clear log", None))
        self.label_15.setText(QCoreApplication.translate("CustomDialog", u"custom engine list", None))
        self.saveButton.setText(QCoreApplication.translate("CustomDialog", u"Save", None))
        self.saveKeySecretCheckBox.setText(QCoreApplication.translate("CustomDialog", u"Save the key and secret in the upper right corner", None))
        self.deleteButton.setText(QCoreApplication.translate("CustomDialog", u"Delete", None))
    # retranslateUi

