# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'one_key_translate.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTextEdit, QWidget)

class Ui_OneKeyTranslateDialog(object):
    def setupUi(self, OneKeyTranslateDialog):
        if not OneKeyTranslateDialog.objectName():
            OneKeyTranslateDialog.setObjectName(u"OneKeyTranslateDialog")
        OneKeyTranslateDialog.resize(1039, 762)
        self.selectFileBtn = QPushButton(OneKeyTranslateDialog)
        self.selectFileBtn.setObjectName(u"selectFileBtn")
        self.selectFileBtn.setGeometry(QRect(520, 25, 81, 91))
        self.selectFileText = QTextEdit(OneKeyTranslateDialog)
        self.selectFileText.setObjectName(u"selectFileText")
        self.selectFileText.setGeometry(QRect(110, 25, 411, 91))
        self.tlNameText = QTextEdit(OneKeyTranslateDialog)
        self.tlNameText.setObjectName(u"tlNameText")
        self.tlNameText.setGeometry(QRect(110, 140, 491, 81))
        self.label_8 = QLabel(OneKeyTranslateDialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 150, 71, 31))
        self.label_8.setWordWrap(True)
        self.label = QLabel(OneKeyTranslateDialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 40, 71, 61))
        self.label.setWordWrap(True)
        self.label_9 = QLabel(OneKeyTranslateDialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 245, 41, 31))
        self.changeTranslationEngineButton = QPushButton(OneKeyTranslateDialog)
        self.changeTranslationEngineButton.setObjectName(u"changeTranslationEngineButton")
        self.changeTranslationEngineButton.setGeometry(QRect(30, 320, 571, 24))
        self.targetComboBox = QComboBox(OneKeyTranslateDialog)
        self.targetComboBox.setObjectName(u"targetComboBox")
        self.targetComboBox.setGeometry(QRect(110, 250, 491, 22))
        self.sourceComboBox = QComboBox(OneKeyTranslateDialog)
        self.sourceComboBox.setObjectName(u"sourceComboBox")
        self.sourceComboBox.setGeometry(QRect(110, 285, 491, 22))
        self.label_10 = QLabel(OneKeyTranslateDialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 280, 41, 31))
        self.localGlossaryCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.localGlossaryCheckBox.setObjectName(u"localGlossaryCheckBox")
        self.localGlossaryCheckBox.setGeometry(QRect(30, 450, 571, 20))
        self.selectFontBtn = QPushButton(OneKeyTranslateDialog)
        self.selectFontBtn.setObjectName(u"selectFontBtn")
        self.selectFontBtn.setGeometry(QRect(520, 660, 81, 91))
        self.label_4 = QLabel(OneKeyTranslateDialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 690, 71, 31))
        self.label_4.setWordWrap(True)
        self.selectFontText = QTextEdit(OneKeyTranslateDialog)
        self.selectFontText.setObjectName(u"selectFontText")
        self.selectFontText.setGeometry(QRect(110, 660, 411, 91))
        self.unpackCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.unpackCheckBox.setObjectName(u"unpackCheckBox")
        self.unpackCheckBox.setGeometry(QRect(620, 30, 411, 20))
        self.unpackCheckBox.setChecked(True)
        self.runtimeExtractionCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.runtimeExtractionCheckBox.setObjectName(u"runtimeExtractionCheckBox")
        self.runtimeExtractionCheckBox.setGeometry(QRect(620, 90, 411, 20))
        self.runtimeExtractionCheckBox.setChecked(True)
        self.extractionCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.extractionCheckBox.setObjectName(u"extractionCheckBox")
        self.extractionCheckBox.setGeometry(QRect(620, 210, 411, 20))
        self.extractionCheckBox.setChecked(True)
        self.replaceFontCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.replaceFontCheckBox.setObjectName(u"replaceFontCheckBox")
        self.replaceFontCheckBox.setGeometry(QRect(620, 270, 411, 20))
        self.replaceFontCheckBox.setChecked(True)
        self.addEntranceCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.addEntranceCheckBox.setObjectName(u"addEntranceCheckBox")
        self.addEntranceCheckBox.setGeometry(QRect(620, 330, 411, 20))
        self.addEntranceCheckBox.setChecked(True)
        self.translateCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.translateCheckBox.setObjectName(u"translateCheckBox")
        self.translateCheckBox.setGeometry(QRect(620, 450, 411, 20))
        self.translateCheckBox.setChecked(True)
        self.filterCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.filterCheckBox.setObjectName(u"filterCheckBox")
        self.filterCheckBox.setGeometry(QRect(30, 480, 261, 20))
        self.filterCheckBox.setChecked(True)
        self.filterLengthLineEdit = QLineEdit(OneKeyTranslateDialog)
        self.filterLengthLineEdit.setObjectName(u"filterLengthLineEdit")
        self.filterLengthLineEdit.setGeometry(QRect(500, 480, 101, 20))
        self.filterLengthLineEdit.setText(u"8")
        self.filterLengthLineEdit.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(OneKeyTranslateDialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 482, 201, 16))
        self.label_14.setAlignment(Qt.AlignCenter)
        self.startButton = QPushButton(OneKeyTranslateDialog)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(620, 620, 401, 131))
        self.officialExtractionCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.officialExtractionCheckBox.setObjectName(u"officialExtractionCheckBox")
        self.officialExtractionCheckBox.setGeometry(QRect(620, 150, 411, 20))
        self.officialExtractionCheckBox.setChecked(True)
        self.filterCheckBox_2 = QCheckBox(OneKeyTranslateDialog)
        self.filterCheckBox_2.setObjectName(u"filterCheckBox_2")
        self.filterCheckBox_2.setGeometry(QRect(30, 540, 261, 20))
        self.filterCheckBox_2.setChecked(True)
        self.filterLengthLineEdit_2 = QLineEdit(OneKeyTranslateDialog)
        self.filterLengthLineEdit_2.setObjectName(u"filterLengthLineEdit_2")
        self.filterLengthLineEdit_2.setGeometry(QRect(500, 538, 101, 20))
        self.filterLengthLineEdit_2.setText(u"3")
        self.filterLengthLineEdit_2.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(OneKeyTranslateDialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(290, 540, 201, 16))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.underlineCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.underlineCheckBox.setObjectName(u"underlineCheckBox")
        self.underlineCheckBox.setGeometry(QRect(30, 510, 581, 20))
        self.underlineCheckBox.setChecked(True)
        self.maxThreadsLineEdit = QLineEdit(OneKeyTranslateDialog)
        self.maxThreadsLineEdit.setObjectName(u"maxThreadsLineEdit")
        self.maxThreadsLineEdit.setGeometry(QRect(210, 350, 391, 20))
        self.maxThreadsLineEdit.setPlaceholderText(u"")
        self.label_2 = QLabel(OneKeyTranslateDialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 352, 161, 16))
        self.label_2.setText(u"MAX_UNPACK_THREADS : ")
        self.overwriteCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.overwriteCheckBox.setObjectName(u"overwriteCheckBox")
        self.overwriteCheckBox.setGeometry(QRect(30, 390, 571, 20))
        self.unpackAllCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.unpackAllCheckBox.setObjectName(u"unpackAllCheckBox")
        self.unpackAllCheckBox.setGeometry(QRect(30, 420, 561, 20))
        self.unpackAllCheckBox.setChecked(False)
        self.rtlCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.rtlCheckBox.setObjectName(u"rtlCheckBox")
        self.rtlCheckBox.setGeometry(QRect(30, 570, 591, 20))
        self.rtlCheckBox.setCursor(QCursor(Qt.ArrowCursor))
        self.label_3 = QLabel(OneKeyTranslateDialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 590, 591, 61))
        self.label_3.setWordWrap(True)
        self.setDefaultLanguageCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.setDefaultLanguageCheckBox.setObjectName(u"setDefaultLanguageCheckBox")
        self.setDefaultLanguageCheckBox.setGeometry(QRect(620, 390, 821, 20))
        self.setDefaultLanguageCheckBox.setChecked(True)
        self.errorRepairCheckBox = QCheckBox(OneKeyTranslateDialog)
        self.errorRepairCheckBox.setObjectName(u"errorRepairCheckBox")
        self.errorRepairCheckBox.setGeometry(QRect(620, 510, 411, 20))
        self.errorRepairCheckBox.setChecked(True)
        self.maxRecursionLineEdit = QLineEdit(OneKeyTranslateDialog)
        self.maxRecursionLineEdit.setObjectName(u"maxRecursionLineEdit")
        self.maxRecursionLineEdit.setGeometry(QRect(620, 590, 401, 20))
        self.maxRecursionLineEdit.setText(u"")
        self.maxRecursionLineEdit.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(OneKeyTranslateDialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(620, 540, 391, 41))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setWordWrap(True)

        self.retranslateUi(OneKeyTranslateDialog)

        QMetaObject.connectSlotsByName(OneKeyTranslateDialog)
    # setupUi

    def retranslateUi(self, OneKeyTranslateDialog):
        OneKeyTranslateDialog.setWindowTitle(QCoreApplication.translate("OneKeyTranslateDialog", u"One Key Translate", None))
        self.selectFileBtn.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"...", None))
#if QT_CONFIG(tooltip)
        self.selectFileText.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.selectFileText.setPlaceholderText(QCoreApplication.translate("OneKeyTranslateDialog", u"input or choose or drag the game you want to extract it's dialogues.Example:F:/DemoGame.exe", None))
        self.tlNameText.setPlaceholderText(QCoreApplication.translate("OneKeyTranslateDialog", u"Input the directory name under game\\tl  Example: 'japanese' or 'chinese'.If the folder already exists, the content will be appended to the original file", None))
        self.label_8.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"tl name", None))
        self.label.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"file", None))
        self.label_9.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"target", None))
        self.changeTranslationEngineButton.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Change Translation Engine", None))
        self.label_10.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"source", None))
        self.localGlossaryCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Local Glossary (replace certain words with preset content)", None))
        self.selectFontBtn.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"...", None))
        self.label_4.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"font", None))
        self.selectFontText.setPlaceholderText(QCoreApplication.translate("OneKeyTranslateDialog", u"input or choose or drag the font which supports the language after translation. Example : DejaVuSans.ttf (ren'py 's default font)", None))
        self.unpackCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Unpack Game Package", None))
        self.runtimeExtractionCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Runtime Extraction", None))
        self.extractionCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Extraction", None))
        self.replaceFontCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Replace Font", None))
        self.addEntranceCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Add Change Langauge Entrance", None))
        self.translateCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Translate", None))
        self.filterCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Enable filter for extract", None))
        self.label_14.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"filter length less than", None))
        self.startButton.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Start", None))
        self.officialExtractionCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Official Extraction", None))
        self.filterCheckBox_2.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Enable filter for translate", None))
        self.label_15.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"filter length less than", None))
        self.underlineCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Skip extract the contents which include underline", None))
        self.overwriteCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Overwrite the rpy file if exsits", None))
        self.unpackAllCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Unpack all files (if disabled only script files will be unpacked)", None))
#if QT_CONFIG(tooltip)
        self.rtlCheckBox.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.rtlCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Enable RTL (Right To Left)", None))
        self.label_3.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"(Fix reversed font problem for some languages like arabic, urdu)", None))
        self.setDefaultLanguageCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"set default language at startup", None))
        self.errorRepairCheckBox.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"Error Repair", None))
        self.label_5.setText(QCoreApplication.translate("OneKeyTranslateDialog", u"max repair count", None))
    # retranslateUi

