# Form implementation generated from reading ui file 'proxy.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProxyDialog(object):
    def setupUi(self, ProxyDialog):
        ProxyDialog.setObjectName("ProxyDialog")
        ProxyDialog.resize(486, 87)
        self.checkBox = QtWidgets.QCheckBox(parent=ProxyDialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.proxyEdit = QtWidgets.QLineEdit(parent=ProxyDialog)
        self.proxyEdit.setGeometry(QtCore.QRect(210, 20, 261, 20))
        self.proxyEdit.setObjectName("proxyEdit")
        self.label = QtWidgets.QLabel(parent=ProxyDialog)
        self.label.setGeometry(QtCore.QRect(120, 22, 91, 16))
        self.label.setObjectName("label")
        self.confirmButton = QtWidgets.QPushButton(parent=ProxyDialog)
        self.confirmButton.setGeometry(QtCore.QRect(200, 50, 75, 24))
        self.confirmButton.setObjectName("confirmButton")

        self.retranslateUi(ProxyDialog)
        QtCore.QMetaObject.connectSlotsByName(ProxyDialog)

    def retranslateUi(self, ProxyDialog):
        _translate = QtCore.QCoreApplication.translate
        ProxyDialog.setWindowTitle(_translate("ProxyDialog", "ProxySettings"))
        self.checkBox.setText(_translate("ProxyDialog", "Enable Proxy"))
        self.proxyEdit.setPlaceholderText(_translate("ProxyDialog", "example : http://localhost:10809"))
        self.label.setText(_translate("ProxyDialog", "proxy address:"))
        self.confirmButton.setText(_translate("ProxyDialog", "confirm"))
